version: "3.7"
services:

  client:
    image: piepongwong/countries-client:latest

  api:
      image: piepongwong/countries-api:latest
      environment:
        - PORT=80  
  
  reverse-proxy:
    image: piepongwong/reverse-proxy
    ports:
        - "80:80"
        - "443:443"